# Local Docker Compose Env
version: "3.8"

services:
  test:
    image: gova11y/postgres:latest
    hostname: ga_pg_test
    ports:
      - 7080:5432
    volumes:
      - /mnt/user/dbstorage/gova11y/test:/var/lib/postgresql/data
    networks:
      - utilities

  prod:
    image: gova11y/postgres:latest
    hostname: ga_pg_prod
    ports:
      - 7081:5432
    volumes:
      - /mnt/user/dbstorage/gova11y/test:/var/lib/postgresql/data
    networks:
      - utilities

networks:
  utilities:
    external: true
