# Local Docker Compose Env
version: '3.8'

services:
    baseline:
      image: gova11y/postgres:latest
      hostname: baseline
      ports:
        - "7050:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/baseline:/var/lib/postgresql/data
      networks:
        - utilities

    development:
      image: gova11y/postgres:development
      hostname: development
      ports:
        - "7051:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/development:/var/lib/postgresql/data
      networks:
        - utilities

    testing:
      image: gova11y/postgres:testing
      hostname: testing
      ports:
        - "7052:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/testing:/var/lib/postgresql/data
      networks:
        - utilities

    production:
      image: gova11y/postgres:latest
      hostname: production
      ports:
        - "7053:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/production:/var/lib/postgresql/data
      networks:
        - utilities

networks:
  utilities:
    external: true