# Local Docker Compose Env
version: '3.8'

services:
    baseline:
      image: gova11y/postgres:latest
      hostname: baseline
      ports:
        - "7050:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/baseline:/var/lib/postgresql/data
      networks:
        - utilities

    development:
      image: gova11y/postgres:development
      hostname: development
      ports:
        - "7051:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/development:/var/lib/postgresql/data
      networks:
        - utilities

    testing:
      image: gova11y/postgres:testing
      hostname: testing
      ports:
        - "7052:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/testing:/var/lib/postgresql/data
      networks:
        - utilities

    production:
      image: gova11y/postgres:latest
      hostname: production
      ports:
        - "7053:5432"
      volumes:
        - /mnt/user/dbstorage/gova11y/production:/var/lib/postgresql/data
      networks:
        - utilities

    postgrest:
      image: postgrest/postgrest:latest
      hostname: postgrest
      ports:
        - "7060:3000"
      environment:
        - PGRST_DB_URI
        - PGRST_CORS_DOMAIN=*
        - PGRST_JWT_SECRET
      networks:
        - utilities

    swagger:
      image: swaggerapi/swagger-ui
      hostname: swagger
      ports:
        - "7061:8080"
      environment:
        - API_URL=http://postgrest:3000
      networks:
        - utilities

networks:
  utilities:
    external: true